@extends('layouts.MainLayout')

@section('header-title')
    Учёба
@endsection

@section('content')
    <h1 style="vertical-align: center">Севастопольский государственный университет</h1>

    <h1 style="vertical-align: center">Институт информационных технологий</h1>

    <div class="borderTable">
        <table style="width: 600px; margin: 20px auto">
            <tr>
                <td rowspan="3">
                    <h4>№</h4>
                </td>
                <td rowspan="3">
                    <h4>Дисциплина</h4>
                </td>
                <td colspan="12">
                    <h4><strong> Часов в неделю </strong></h4>
                </td>
            </tr>
            <tr>
                <td colspan="6">
                    <h4>1 курс</h4>
                </td>
                <td colspan="6">
                    <h4>2 курс</h4>
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <h4>1 сем</h4>
                </td>
                <td colspan="3">
                    <h4>2 сем</h4>
                </td>
                <td colspan="3">
                    <h4>3 сем</h4>
                </td>
                <td colspan="3">
                    <h4>4 сем</h4>
                </td>
            </tr>
            <tr>
                <td>
                    <h4>1</h4>
                </td>
                <td>
                    <h4>Экология</h4>
                </td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    <h4>1</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>1</h4>
                </td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>
                    <h4>2</h4>
                </td>
                <td>
                    <h4>Высшая математика</h4>
                </td>
                <td>
                    <h4>3</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>3</h4>
                </td>
                <td>
                    <h4>3</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>3</h4>
                </td>
                <td>
                    <h4>2</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>2</h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
            </tr>
            <tr>
                <td>
                    <h4>3</h4>
                </td>
                <td>
                    <h4>Русский язык и культура речи</h4>
                </td>
                <td>
                    <h4>1</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>2</h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
            </tr>
            <tr>
                <td>
                    <h4>4</h4>
                </td>
                <td>
                    <h4>Основы дискретной математики</h4>
                </td>
                <td>
                    <h4>2</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>1</h4>
                </td>
                <td>
                    <h4>3</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>2</h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
            </tr>
            <tr>
                <td>
                    <h4>5</h4>
                </td>
                <td>
                    <h4>Основы программирования и алгоритмические языки</h4>
                </td>
                <td>
                    <h4>3</h4>
                </td>
                <td>
                    <h4>2</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>3</h4>
                </td>
                <td>
                    <h4>3</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>1</h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
            </tr>
            <tr>
                <td>
                    <h4>6</h4>
                </td>
                <td>
                    <h4>Основы экологии</h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4>1</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
            </tr>
            <tr>
                <td>
                    <h4>7</h4>
                </td>
                <td>
                    <h4>Теория вероятностей и математическая статистика</h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4>3</h4>
                </td>
                <td>
                    <h4>1</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
            </tr>
            <tr>
                <td>
                    <h4>8</h4>
                </td>
                <td>
                    <h4>Физика</h4>
                </td>
                <td>
                    <h4>2</h4>
                </td>
                <td>
                    <h4>2</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>2</h4>
                </td>
                <td>
                    <h4>2</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>2</h4>
                </td>
                <td>
                    <h4>1</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
            </tr>
            <tr>
                <td>
                    <h4>9</h4>
                </td>
                <td>
                    <h4>Основы электротехники и электроники</h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4>2</h4>
                </td>
                <td>
                    <h4>1</h4>
                </td>
                <td>
                    <h4>1</h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
            </tr>
            <tr>
                <td>
                    <h4>10</h4>
                </td>
                <td>
                    <h4>Численные методы в информатике</h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4>2</h4>
                </td>
                <td>
                    <h4>2</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>1</h4>
                </td>
            </tr>
            <tr>
                <td>
                    <h4>11</h4>
                </td>
                <td>
                    <h4>Методы исследования операций</h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4></h4>
                </td>
                <td>
                    <h4>1</h4>
                </td>
                <td>
                    <h4>1</h4>
                </td>
                <td>
                    <h4>0</h4>
                </td>
                <td>
                    <h4>2</h4>
                </td>
                <td>
                    <h4>1</h4>
                </td>
                <td>
                    <h4>1</h4>
                </td>
            </tr>
        </table>
    </div>
@endsection